### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by developer9969** [gordon-matt/BootstrapHelpers#4]
Hi
Come across your library as I was looking for accordion asp.net mvc.Learning mvc so bear with me.
I am loading the according from db and the text is not displaying.
Am I missing the obvious?

public class FaqModel
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }

  public ActionResult Faq()
        {
            var faqModels = new List<FaqModel>();
            faqModels.Add(new FaqModel {Id = "1", Title = "Test1",Description="This is a description for Test1"});
            faqModels.Add(new FaqModel {Id = "2", Title = "Test2",Description = "This is a description for Test2" });
           return  View(faqModels);
        }

@model List<FaqModel>

@{
    ViewBag.Title = "Faq";
}

<h2>Faq</h2>

<div class="span11" id="demoAccordion">
    <h3>ACCORDION DEMO</h3>
    <br />
        @using (var accordion = Html.Bootstrap().Begin(new Accordion("accordion1")))
        {
            foreach (var faqModel in Model)
            {
                using (var panel = accordion.BeginPanel(faqModel.Title, faqModel.Id))
                {
                    <p>@Html.DisplayText(faqModel.Description)</p> //THIS DOESNT WHY
                    @Html.Bootstrap().Quote(faqModel.Description,"")  //THIS DISPLAYS
                }
            }
        }
    
</div>

Many thanks for any suggestions

**Comment by gordon-matt** [comment]
Closing issue, as this project is no longer supported.
